### PR TITLE
#42 Can't delete duplicates of default sets

### PR DESCRIPTION
**Pull request by jakxnz**
https://github.com/heyday/silverstripe-menumanager/issues/42

### CODE REVIEW

**Comment by aria5305** [comment]
@HJGreen Hi Harry, if we catch this PR up to the main repository, will you be able to review and merge this in?

**Comment by HJGreen** [comment]
@aria5305 Absolutely! This looks like key functionality which has previously been overlooked - especially the constraint to prevent creating non-unique names

**Comment by jakxnz** [comment]
@HJGreen @aria5305, This seems like it's still ready to merge to me. Was there a change we needed to make, or can this merge as is?

**Comment by HJGreen** [comment]
Yup, looks good! Thank you @jakxnz and apologies for the delay!

**Pull request merged**
