### PR TITLE
SS4 updates

### PR DESCRIPTION
**Pull request by hdpero**
- change composer name to `heyday/menumanager`
- change reference of Requirements assets
- change `"code"` folder to `"src"`
- change to `silverstripe-vendormodule` type

### CODE REVIEW

**Comment by stecman** [comment]
Hey @hdpero, same question about the package name change as in https://github.com/heyday/silverstripe-responsive-images/pull/21. I'll wait for your answer there.

Otherwise changes look ok :+1:

**Comment by stecman** [comment]
@clairefinnie are you guys moving this to `heyday/menumanager` on Packagist??

**Comment by clairefinnie** [comment]
@stecman Yes, as soo n as I figure out how to!?

**Comment by stecman** [comment]
@clairefinne [see this](https://github.com/composer/packagist/issues/47) linked in the other PR above. Currently you have to mark the old name as abandoned and add the new name as a new package, then every project that wants to receive new versions has to update their composer.json with the new name - I'd recommend not doing that just for the sake of removing `silverstripe` from the name.

**Pull request merged**
